### ISSUE TITLE
Request printed copy for user not logged in with no permissions for document

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-dms-cart#14]
If a user is not logged in and does not have permission to view/download a document they should not be able to request a printed copy.

*Remove 'Request printed copy' link for this particular scenario.

**Comment by fspringveldt** [comment]
@sachajudd what do you think of removing the link and adding a strikethrough to make it more obvious?

**Comment by sachajudd** [comment]
I think it should be removed @fspringveldt
