### ISSUE TITLE
When submitting an "order", the current state of the document/item should be saved

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-dms-cart#39]
Currently a DMSCartSubmission contains one DMSCartSubmissionItem per document requested. The DMSCartSubmission has_one DMSDocument.

The problem with this is that once the order is placed it will continue to be updated whenever that document changes, which ruins the historic data integrity.

For example, if I submit a request for a selection of document then rename one of the documents, replace it entirely (DMS functionality) or delete it, the cart submission no longer reflects what I requested.

We need to save a select of the DMSDocument data against the submission item record at the time it is created to ensure that this doesn't happen.

Most of the data in the DMSDocument model is not relevant to the actual document, but more aimed at how or when it is displayed on the frontend. These attributes (e.g. embargo, permissions, related documents) should not be copied over when a submission is made. Arguably even the filename should not be copied, as the file itself is removed when a document gets deleted. It's not feasible to duplicate the physical files for each order, unless we come up with some complicated storage mechanism to duplicate to a persistent storage area if it doesn't exist there already, then reference that file from any submissions that require it.

Needs feedback.

---

As someone who manages cart submissions,
I want to look through historic cart submissions,
And I expect that they should never change,
So that I can always see what people have requested

**Comment by fspringveldt** [comment]
@robbieaverill I see DMSDocument is versioned. We should then record the version of the DMSDocument against the DMSCartSubmission instead of the live one. This should solve this problem entirely. 

What are your thoughts?

**Comment by robbieaverill** [comment]
@fspringveldt the versioning is only for the physical file attached to the document. This won't work for changing document metadata or deleting it completely.
